# Generated by Django 5.2.3 on 2025-07-01 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_id',
            field=models.CharField(help_text='FCM Registration Token for this device', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('user', 'registration_id')},
        ),
    ]
