# Generated by Django 5.2.3 on 2025-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_fcmdevice_registration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='platform',
            field=models.CharField(blank=True, help_text='Platform: ios, android, web', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string for platform detection', null=True),
        ),
    ]
