# Generated by Django 5.2.3 on 2025-07-12 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_inappnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='app_version',
            field=models.CharField(blank=True, help_text='App version if applicable', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='browser',
            field=models.CharField(blank=True, help_text='Browser name and version', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device type: mobile, tablet, desktop', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='last_used',
            field=models.DateTimeField(auto_now=True, help_text='Last time this device was used'),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_id',
            field=models.CharField(help_text='FCM Registration Token for this device', max_length=500),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['user', 'active'], name='notificatio_user_id_9487e6_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['platform', 'active'], name='notificatio_platfor_c84fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['created_at'], name='notificatio_created_4458d4_idx'),
        ),
    ]
