# Generated by Django 5.2.3 on 2025-07-15 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='morning_fasting_weight',
            field=models.FloatField(help_text='체중은 10kg ~ 300kg 범위 내에서 입력해 주세요.', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
    ]
